analytics: {}
color:
  brandColors:
    - '#6b89d8'
    - '#ffffff'
    - '#c5c8bd'
    - '#1b1f30'
    - '#4c6199'
  brandStrength: 0.5
  lightness: 0.5
  rhythmicContrast: 0.25
  saturation: 0.25
cta: {}
layout_spectrum: 1
name: iTrio
opengraph: {}
purpose: []
typography_spectrum: 0.71583
