layout_spectrum: 0.02720723905130336
typography_spectrum: 0.41611200482851946
color:
  brandColors:
    - '#26242F'
    - '#CCD32E'
    - '#CD2C17'
    - '#4D6370'
    - '#BE6718'
  brandStrength: 0.19803855216213603
  lightness: 0.42439757902156744
  saturation: 0.18880598844176544
  rhythmicContrast: 1
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-82649324-1
  facebook: null
  twitter: null
author:
  name: i.Trio
  email: info@itrio.ch
logo: null
name: i.Trio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The Band
    id: df053d0d-fe9e-4c02-8ca6-6fae75a10669
    type: content
  - name: What the press says
    id: f8c6a4a4-c321-42c3-92ff-88b4cae6d154
    type: content
  - name: Bandcamp
    url: 'http://itrio.bandcamp.com'
    type: external
  - name: Presskit
    url: 'http://presskit.itrio.ch/'
    type: external
  - name: Contact and tour dates
    id: 9f66cc6e-1ddb-4073-a210-97b3d6c88dd5
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e667954-bbba-4844-a71a-696440deb2ab.jpg
title: i.Trio
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FJN_nFmrncmc%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJN_nFmrncmc&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FJN_nFmrncmc%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://www.youtube.com/watch?v=JN_nFmrncmc'
      keywords:
        - winterthur
        - duration
        - itrio
        - fabe
        - views
        - mira
        - live
        - montreux
        - vega
        - nov2013
      related: []
      author:
        - name: i.Trio
          url: 'https://www.youtube.com/channel/UC6oOOT1yF5g71JJhHIPpoLg'
          avatar: {}
      '@context': 'http://schema.org'
      title: Live at Esse Musicbar Winterthur Medley
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=JN_nFmrncmc&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=JN_nFmrncmc&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=JN_nFmrncmc&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=JN_nFmrncmc&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=JN_nFmrncmc&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=JN_nFmrncmc'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=JN_nFmrncmc
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=JN_nFmrncmc
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      description: >-
        A little summary of our last gig at The Esse Musicbar in Winterthur on
        the 02.02.17 www.itrio.ch booking@itrio.ch
      inLanguage: en
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Power-Fusion-Jazz from Switzerland
purpose:
  - type: external
    url: 'http://music.itrio.ch'
    label: Latest release
  - type: contact
    url: 'mailto:booking@itrio.ch'
    label: Book us!
