typography_spectrum: 0.36439
color:
  brandColors:
    - '#6b89d8'
    - '#ffffff'
    - '#000000'
    - '#aeb8c3'
    - '#202337'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.70517
analytics:
  google: null
  facebook: null
  twitter: null
name: 'iTrio - Fusion-Jazz from Switzerland '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Presskit
    url: 'http://presskit.itrio.ch/'
    type: external
  - name: The band
    id: 0654faad-a48b-4932-a8cb-ea31aaefb363
    type: content
  - name: Contact
    id: a2d46619-1816-423a-b40e-c5905b866855
    type: content
favicon: null
purpose: []
