typography_spectrum: 0.36439
color:
  brandColors:
    - '#6b89d8'
    - '#ffffff'
    - '#000000'
    - '#aeb8c3'
    - '#202337'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.70517
analytics:
  google: UA-82649324-1
  facebook: null
  twitter: null
name: 'iTrio - Fusion-Jazz from Switzerland '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The band
    id: 0654faad-a48b-4932-a8cb-ea31aaefb363
    type: content
  - name: What the press says
    id: f8c6a4a4-c321-42c3-92ff-88b4cae6d154
    type: content
  - name: Contact
    id: a2d46619-1816-423a-b40e-c5905b866855
    type: content
  - name: Presskit
    url: 'http://presskit.itrio.ch/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e667954-bbba-4844-a71a-696440deb2ab.jpg
title: i.Trio
purpose: []
