name: 'iTrio - Fusion-Jazz from Switzerland '
favicon: null
layout_spectrum: 0.23783
typography_spectrum: 0.62404
title: iTrio - Fusion-Jazz from Switzerland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b89d8'
    - '#ffffff'
    - '#c5c8bd'
    - '#1b1f30'
    - '#4c6199'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
