name: 'iTrio - Fusion-Jazz from Switzerland '
favicon: null
layout_spectrum: 0.70517
typography_spectrum: 0.36439
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b89d8'
    - '#ffffff'
    - '#000000'
    - '#aeb8c3'
    - '#202337'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
