analytics: {}
color:
  brandColors:
    - '#6b89d8'
    - '#ffffff'
    - '#c5c8bd'
    - '#1b1f30'
    - '#4c6199'
  brandStrength: 1
  lightness: 0.25
  rhythmicContrast: 0.75
  saturation: 0.125
cta: {}
layout_spectrum: 0.792792
name: 'iTrio - Fusion-Jazz from Switzerland '
opengraph: {}
purpose: []
typography_spectrum: 0.36439
