name: iTrio
favicon: null
layout_spectrum: 0.53547
typography_spectrum: 0.71583
title: iTrio - Fusion-Jazz from Switzerland
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b89d8'
    - '#ffffff'
    - '#c5c8bd'
    - '#1b1f30'
    - '#4c6199'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
