layout_spectrum: 0.572036423293302
typography_spectrum: 0.5504671461958586
color:
  brandColors:
    - '#6B89D8'
    - '#FFFFFF'
    - '#282C40'
    - '#46647A'
    - '#D4D6DA'
  brandStrength: 0.782509098569171
  lightness: 0.3085971454518045
  saturation: 0.6789781153601328
  rhythmicContrast: 0.858100651322154
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-82649324-1
  facebook: null
  twitter: null
logo: null
name: i.Trio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The Band
    id: df053d0d-fe9e-4c02-8ca6-6fae75a10669
    type: content
  - name: What the press says
    id: f8c6a4a4-c321-42c3-92ff-88b4cae6d154
    type: content
  - name: Contact and tour dates
    id: 9f66cc6e-1ddb-4073-a210-97b3d6c88dd5
    type: content
  - name: Presskit
    url: 'http://presskit.itrio.ch/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2e667954-bbba-4844-a71a-696440deb2ab.jpg
title: i.Trio
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0c50ba4-b79d-4245-9e31-e40b209cc57f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0c50ba4-b79d-4245-9e31-e40b209cc57f.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/1177714d-c11d-42d3-8c46-1fcbf76df2cb.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/1177714d-c11d-42d3-8c46-1fcbf76df2cb.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ad27fa30-8735-4db2-99a1-6809aee743ef.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ad27fa30-8735-4db2-99a1-6809aee743ef.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Rock-Fusion-Jazz from Switzerland
purpose:
  - type: external
    url: 'http://music.itrio.ch'
    label: Latest release
  - type: contact
    url: 'mailto:booking@itrio.ch'
    label: Book us!
